language: java
services:
- docker
env:
  global:
      - COMMIT=${TRAVIS_COMMIT::8}
script:
  - cd gw2verify-api-client-java
  - mvn clean compile
  - cd ..
  - mvn clean compile assembly:single

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export REPO=$DOCKER_USERNAME/fsp-discord-bot
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$COMMIT -f docker/Dockerfile .
  - docker images
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO